# CentiloidCalculator 配置文件 (TOML格式) - 快速精确版本
# 此文件包含所有可配置的参数

# 模型文件路径（相对于可执行文件目录）
[models]
rigid = "assets/models/registration/rigid.onnx"
affine_voxelmorph = "assets/models/registration/affine_voxelmorph.fast_and_acc.onnx"
abeta_decoupler = "assets/models/decouple/abeta.onnx"
tau_decoupler = "assets/models/decouple/tau.onnx"

# 模板文件路径
[templates]
adni_pet_core = "assets/nii/ADNI_empty.nii"
padded = "assets/nii/padded_MNI152_T1_2mm.nii"

# 掩膜文件路径
[masks]
cerebral_gray = "assets/nii/voi_CerebGry_2mm.nii"
centiloid_voi = "assets/nii/voi_ctx_2mm.nii"
whole_cerebral = "assets/nii/voi_WhlCbl_2mm.nii"
centaur_voi = "assets/nii/CenTauR.nii"
centaur_ref = "assets/nii/voi_CerebGry_tau_2mm.nii"

# 处理参数
[processing]
max_iter = 5
ac_diff_threshold = 2.0
temp_dir = "./tmp"

# MNI裁剪参数
[processing.crop_mni]
start_x = 8
start_y = 16
start_z = 8
size_x = 79
size_y = 95
size_z = 79

# Centiloid参数
[centiloid.tracers.pib]
slope = 120.6
intercept = -127.7

[centiloid.tracers.fbp]
slope = 215.3
intercept = -231.9

[centiloid.tracers.fbb]
slope = 193.1
intercept = -199.7

[centiloid.tracers.fmm]
slope = 151.7
intercept = -153.2

[centiloid.tracers.nav]
slope = 109.8
intercept = -118.8

# CenTauR参数
# The CenTauR dataset is not publicly available
# The conversion formula is based on the FTP calibration results
[centaur.tracers.ftp]
baseline = 1.08
max = 2.30

[centaur.tracers.gtp1]
baseline = 1.10
max = 1.80

[centaur.tracers.mk6240]
baseline = 0.93
max = 3.62

[centaur.tracers.pi2620]
baseline = 1.20
max = 2.28

[centaur.tracers.ro948]
baseline = 1.05
max = 2.60

# CenTauRz参数
# The only tested tracer is FTP
# The rest tracers are approximated
# from the FTP calibration results
[centaurz.tracers.ftp]
slope = 11.99
intercept = -14.35

[centaurz.tracers.gtp1]
slope = 9.39
intercept = -10.75

[centaurz.tracers.mk6240]
slope = 8.87
intercept = -8.95

[centaurz.tracers.pi2620]
slope = 7.44
intercept = -8.68

[centaurz.tracers.ro948]
slope = 11.48
intercept = -14.13

[centaurz.tracers.pmpbb3]
slope = 14.72
intercept = -13.50

# SUVr参数配置
[suvr.regions.centiloid]
voi_mask = "centiloid_voi"
ref_mask = "whole_cerebral"

[suvr.regions.centaur]
voi_mask = "centaur_voi"
ref_mask = "centaur_ref"
